
install:
	python setup.py install

py2:
	python2 setup.py install

uninstall:
	$(RM) /usr/lib/python3.6/site-packages/ovg*
	$(RM) /usr/lib/python3.6/site-packages/__pycache__/ovg*
	$(RM) /usr/lib/python2.7/site-packages/ovg*

.PHONY: install py2
